### PR TITLE
fix(dynamic_obstacle_avoidance): improve avoidance for moving NPCs

### PR DESCRIPTION
**Pull request by beyzanurkaya**
## Description
Fixes :
- https://github.com/autowarefoundation/autoware.universe/issues/8739

## Related links
Parent Issue :
- https://github.com/autowarefoundation/autoware.universe/issues/7485

### when dynamic_obstacle_avoidance is enable

https://github.com/user-attachments/assets/9a586851-287f-4523-b4c3-61658f9ca1b5

https://github.com/user-attachments/assets/3880209c-1532-4a5f-ae54-163a9cfa6fe1

### ROS Parameter Changes
| Parameter Name       | Updated Value | Update Description                                  | 
| -------------------- | ------------- | --------------------------------------------------- | 
|lat_offset_from_obstacle      | 0.3 | lower lateral offset to avoid moving NPCs in narrow road                            | 
|margin_distance_around_pedestrian      | 0.8 | lower lateral offset to for pedestrian                          | 
|end_time_to_consider      | 1.0 | lower end_time_to_consider                            | 

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by brkay54 — APPROVED** [review]
With this PR, dynamic avoidance related scenarios have passed: [AWF_Test_Report](https://evaluation.ci.tier4.jp/evaluation/reports/31cc91b6-fb02-5d30-a45c-3b81430ed0f0/tests/db416639-0812-597d-8932-b5a7b30676de?page_size=50&project_id=awf)

**Comment by brkay54** [comment]
@takayuki5168 san, could you check this PR when you are available or can you assign someone to review?

**Review by yuki-takagi-66 — COMMENTED** [review]
I feel these parameters are acceptable only the velocity is sufficient slow.
I suggest to apply this change to your fork branch.
As another option I request to relax the value so that there is no problem even at 40 km/h.

**Comment by beyzanurkaya** [comment]
> I feel these parameters are acceptable only the velocity is sufficient slow. I suggest to apply this change to your fork branch. As another option I request to relax the value so that there is no problem even at 40 km/h.

Thank you for comment @yuki-takagi-66 -san. Is this comment valid for all 3 modified values ​​or do you have doubts about any of them specifically?

**Comment by beyzanurkaya** [comment]
In this scenario, NPC's velocity is 40 km/h but still passing

https://github.com/user-attachments/assets/30b799b6-58aa-47fd-894f-b53dcadad215

**Pull request merged**
