### PR TITLE
feat: add awsim_labs.launch.xml file

### PR DESCRIPTION
**Pull request by xmfcx**
## Description

Part of: 
- https://github.com/autowarefoundation/autoware/issues/4659

Should be merged after:
- https://github.com/autowarefoundation/autoware/pull/4660

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by yukkysaito** [comment]
The existing e2e_simulator.launch.xml is the launch for AWSIM. What will be the position of this one?
https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/launch/e2e_simulator.launch.xml

**Comment by xmfcx** [comment]
@yukkysaito the existing one can stay as it is. Or, we could rename it to just `awsim.launch.xml` too.

**Comment by xmfcx** [comment]
This new launch file is for AWSIM Labs. `awsim_labs.launch.xml` as a new launch file, copied and edited (`sensor_kit`) field to match AWSIM Labs executable (which will be released soon)

**Comment by xmfcx** [comment]
Never mind, I've realized this e2e simulator launch file is also being used by other simulators like carla: https://github.com/Robotics010/carla_autoware_bridge/blob/master/getting-started.md#33-launch-autoware-universe

And I could just override the `vehicle_model` for awsim_labs vehicle model.

I'm closing this.

**Pull request closed without merging**
