### PR TITLE
chore: merge 0.39.0 into humble (with merged commit)

### PR DESCRIPTION
**Pull request by sasakisasaki**
## Description

https://github.com/autowarefoundation/autoware_launch/pull/1248

## Notes for reviewers

@mitsudome-r @youtalk I think this PR's purpose is just for merged commit. But I'm welcome to perform any proposed tests and so on. Thanks!

## Effects on system behavior

None.

### CODE REVIEW

**Comment by sasakisasaki** [comment]
Sorry, it seems my commit is pushed without DCO. Let me re-push with the fix.

**Review by youtalk — APPROVED** [review]
You can update the DCO status here. I did it. 
https://github.com/autowarefoundation/autoware_launch/pull/1268/checks?check_run_id=34178810817

**Comment by youtalk** [comment]
MERGE COMMIT!

**Comment by sasakisasaki** [comment]
@youtalk Thank you so much!!! Only one concern I have, ... . There are two commits with the same message as follows.
- https://github.com/autowarefoundation/autoware_launch/pull/1268/commits/5c4a77ff9cdd1827768c4d8773d27f3679af6d4f
- https://github.com/autowarefoundation/autoware_launch/pull/1268/commits/d270635e06a64e7fc9f0dea05268365db1b03a05

Do you think should I fix this confusing history?

**Comment by youtalk** [comment]
`git push -f` to modify the commits is better.

**Comment by sasakisasaki** [comment]
@youtalk Thank you for your advice, now the commit history becomes cleaner :+1:

**Review by mitsudome-r — APPROVED** [review]

**Pull request merged**
