### PR TITLE
chore: merge tier4/autoware_launch v0.38.0 changes to awf/autoware_launch main branch excepts .github changes

### PR DESCRIPTION
**Pull request by youtalk**
## Description

This PR contains the differences from the [v0.38.0 tag of tier4/autoware_launch](https://github.com/tier4/autoware_launch/tree/v0.38.0) to the [main branch of awf/autoware_launch](https://github.com/autowarefoundation/autoware_launch), excluding changes to `.github` directory.

https://github.com/autowarefoundation/autoware_launch/compare/main...tier4:autoware_launch:v0.38.0

This PR is the second step in implementing changes based on https://github.com/orgs/autowarefoundation/discussions/5292. Next, I plan to update the versions in package.xml on the main branch of awf/autoware_launch.

Ref. https://github.com/autowarefoundation/autoware.universe/pull/9261

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by youtalk** [comment]
The forked `tier4/autoware_launch` repository likely contains specific adjustments tailored for TIER IV products. If you have any opinions, such as that this parameter should not be reflected upstream, please let me know.

**Comment by xmfcx** [comment]
Is it possible for us to get a reason for why each parameters are being changed?

For example, the max velocity was limited to 15 km/h for this reason:
- https://github.com/autowarefoundation/autoware_launch/pull/763

It was done for safety reasons while transitioning from obstacle_stop_planner to obstacle_cruise_planner. And the AEB doesn't work reliably for velocities higher than 15km/h.

This goes for all the changes, the PR description and title should contain the reasons these were changed. Not just "merging from tier4 fork for version control".

**Comment by xmfcx** [comment]
@youtalk -san, since
- https://github.com/autowarefoundation/autoware_launch/pull/1229 is merged, can we close this PR?

**Comment by youtalk** [comment]
@xmfcx I want to minimize the differences with the tier4 forked repository, but since there might be some discussion, I’ll close this for now and reconsider.

**Pull request closed without merging**
