### PR TITLE
feat: add config for processing_time_checker

### PR DESCRIPTION
**Pull request by takayuki5168**
## Description

launcher PR for https://github.com/autowarefoundation/autoware.universe/pull/7957

## Tests performed

See https://github.com/autowarefoundation/autoware.universe/pull/7957

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by takayuki5168** [comment]
@kosuke55 
Approve this PR as well after you review it.

**Review by kosuke55 — APPROVED** [review]

**Comment by takayuki5168** [comment]
@ito-san @isamu-takagi @tkimura4 @shmpwk 
Can you approve the PR?

**Review by shmpwk — APPROVED** [review]
LGTM

**Review by tkimura4 — APPROVED** [review]

**Review by isamu-takagi — APPROVED** [review]
LGTM

**Pull request merged**
