### PR TITLE
feat(autoware_launch): add obstacle_collision_checker to launch

### PR DESCRIPTION
**Pull request by brkay54**
Signed-off-by: Berkay Karaman <berkay@leodrive.ai>

## Description
This PR about adding obstacle_collision_checker to control.launch.py. This will be optional.
This PR should merge after https://github.com/autowarefoundation/autoware.universe/pull/2193 merged!

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by shmpwk — COMMENTED** [review]
Do you think this option is useful for [planning_simulator](https://github.com/autowarefoundation/autoware_launch/blob/fa7cedc4776dfac14ebd50a49a57678bfa574f5a/autoware_launch/launch/planning_simulator.launch.xml) and [logging_simultor](https://github.com/autowarefoundation/autoware_launch/blob/fa7cedc4776dfac14ebd50a49a57678bfa574f5a/autoware_launch/launch/logging_simulator.launch.xml) as well?

**Comment by brkay54** [comment]
> Do we need this option for [planning_simulator](https://github.com/autowarefoundation/autoware_launch/blob/fa7cedc4776dfac14ebd50a49a57678bfa574f5a/autoware_launch/launch/planning_simulator.launch.xml) and [logging_simultor](https://github.com/autowarefoundation/autoware_launch/blob/fa7cedc4776dfac14ebd50a49a57678bfa574f5a/autoware_launch/launch/logging_simulator.launch.xml) as well?

Yes I think we should add, I am gonna add the option to both. Thank you for suggestion 👍🏼

**Review by takayuki5168 — APPROVED** [review]
LGTM

**Review by shmpwk — APPROVED** [review]

**Comment by brkay54** [comment]
@takayuki5168 @shmpwk 
https://github.com/autowarefoundation/autoware.universe/pull/2193 was merged, can we merge this too? I don't have write access

**Pull request merged**
