### PR TITLE
feat: update rviz splash and vehicle UI display

### PR DESCRIPTION
**Pull request by KhalilSelyan**
## Description

Part of:
- https://github.com/autowarefoundation/autoware/issues/3984

Updated the autoware splash screen, and the display plugin for the vehicle ui

## Tests performed
Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by xmfcx** [comment]
Thanks! I will test it today

**Comment by xmfcx** [comment]
I've renamed it back to autoware.png from autoware_splash.png with https://github.com/autowarefoundation/autoware_launch/pull/836/commits/cb4049e31bdc40c4bbecee6ff78cdbe008732cdf

Before:
Screenshot from 2024-01-30 20-11-30

After:
Screenshot from 2024-01-30 20-14-21

There are some slight variations from the original design but we can address them later in the Universe:
- gear should be a bit more rounded
- speed limit and traffic light should have same radius
- speed limit text should be larger
- inside of the speed limit logo is fully transparent, should be opaque
- left-right signals should be more faded (when not active), right now they are white

I should have made these comments in the initial Universe review but I wanted to have it all merged first.

Screenshot from 2024-01-30 20-15-19

Thanks for all the work, I think we can merge it now, it looks great!

**Review by xmfcx — APPROVED** [review]

**Comment by TakaHoribe** [comment]
so cool!

**Comment by xmfcx** [comment]
About the splash screen image, for reference:

We followed the [brand guidelines of the Autoware logo](https://autoware.org/wp-content/uploads/2023/06/Brand-Guideline-THE-AUTOWARE-FOUNDATION.pdf).
Screenshot from 2024-01-30 10-30-09

Also used the https://coolors.co/3f2ee3-00c8ff-00e678-ff5c0f-00002a-0094ff oxford blue from the Autoware website's new color palette for the background.

Adding a transparent bg version here in case it might be useful in the future.
autoware_splash_transparent_bg

(this image won't be visible on light backgrounds)

**Pull request merged**
