### PR TITLE
refactor(autoware_launch): change pure_pursuit debug marker topic name

### PR DESCRIPTION
**Pull request by brkay54**
Signed-off-by: Berkay Karaman <berkay@leodrive.ai>

## Description

In current rviz file, `pure_pursuit` debug topic name is wrong. I want to change it.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kenji-miyake** [comment]
I'm sorry I'm not familiar with this node (especially after ported to `autoware.universe`).

@TakaHoribe @takayuki5168 Could you review this? Seeing the code, should we also rename `mpc_follower`?
https://github.com/autowarefoundation/autoware.universe/blob/ed6b5c81fc19353628fb32af78374171f4f8aaa1/launch/tier4_control_launch/launch/control.launch.py#L122
https://github.com/autowarefoundation/autoware.universe/blob/ed6b5c81fc19353628fb32af78374171f4f8aaa1/control/trajectory_follower_nodes/src/controller_node.cpp#L50
image

**Review by takayuki5168 — APPROVED** [review]
LGTM

**Comment by takayuki5168** [comment]
> Actually, I couldn't see any debug markers in mpc_follower, so I didn't change anything in Debug/MPC.

I think so too.
We can remove the visualization of mpc_follower's debug marker with another PR.

**Comment by brkay54** [comment]
@takayuki5168 @kenji-miyake Can you merge this PR please 🙏🏼 . I do not have write access.

**Comment by kenji-miyake** [comment]
Oh, sorry.

@xmfcx Should I give `autoware-developers-leodrive` write access?

**Pull request merged**
