### PR TITLE
feat(psim, dummy_diag, diagnostic_graph_aggregator)!: launch dummy_diag_publisher

### PR DESCRIPTION
**Pull request by yuki-takagi-66**
## Description
This PR change to launch dummy_diag_publisher to use same diagnostic_graph_aggregator setting in psim.launch and autoware.launch.

## Related links
part of this issue https://github.com/autowarefoundation/autoware_launch/issues/1221

## Tests performed
psim and scenario_simulator

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].
- [ ] The PR has been properly tested.
- [ ] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by isamu-takagi** [comment]
@yuki-takagi-66 I think the `-psim` files can be deleted. Is there any reason to leave them commented out?

**Comment by yukkysaito** [comment]
The purpose of the PR and the changes themselves look good. I haven’t verified the working.

**Review by yukkysaito — APPROVED** [review]

**Comment by mitsudome-r** [comment]
I agree with Takagi-san. 
We should either:
* remove the `-psim` file if we are not using them, or
* update the `-psim` file to match with the `-main` and keep using it

**Comment by yuki-takagi-66** [comment]
Thank you for the comments.
I've delete the both "-psim.yaml" files.

**Comment by yuki-takagi-66** [comment]
@isamu-takagi @mitsudome-r 
Thank you for the comments.
I've delete the both "-psim.yaml" files.

**Review by mitsudome-r — APPROVED** [review]

**Pull request merged**
