### PR TITLE
refactor(image_projection_based_fusion): rework params

### PR DESCRIPTION
**Pull request by badai-nguyen**
## Description

- This rename the param file as https://github.com/autowarefoundation/autoware.universe/pull/6289

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by Shin-kyoto** [comment]
@badai-nguyen 

Please add these params to https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/perception/object_recognition/detection/lidar_model/pointpainting.param.yaml, too

```yaml
    # fusion interface common params
    debug_mode: false
    image_buffer_size: 15
    filter_scope_min_x: -100.0
    filter_scope_min_y: -100.0
    filter_scope_min_z: -100.0
    filter_scope_max_x: 100.0
    filter_scope_max_y: 100.0
    filter_scope_max_z: 100.0
```

That is because pointpainting uses roi_sync_param in https://github.com/autowarefoundation/autoware.universe/blob/1ed6fac11a9851c12ede1ec34409204d799d9863/perception/image_projection_based_fusion/launch/pointpainting_fusion.launch.xml#L26

[I checked this PR with evaluator](https://evaluation.tier4.jp/evaluation/oidc/auth/cb/?code=ory_ac_dqcTUSmpfothS_fxY_KIWKER1eENYQQQS6s4LFWsY1g.-gFuMYY_u9fyfAujaRKZ8HeNbnAFTbwmwuIWgs3e5Gk&scope=openid+profile+email+offline_access&state=f9b871c576544626afba41d79798dde7), and I got the error below.

```bash
[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'pointpainting' of type 'image_projection_based_fusion::PointPaintingFusionNode' in container 'pointcloud_container': Component constructor threw an exception: Statically typed parameter 'filter_scope_min_x' must be initialized.
```

**Review by Shin-kyoto — CHANGES_REQUESTED** [review]
@badai-nguyen 

Please add these params to https://github.com/autowarefoundation/autoware_launch/blob/main/autoware_launch/config/perception/object_recognition/detection/lidar_model/pointpainting.param.yaml, too

```yaml
    # fusion interface common params
    debug_mode: false
    image_buffer_size: 15
    filter_scope_min_x: -100.0
    filter_scope_min_y: -100.0
    filter_scope_min_z: -100.0
    filter_scope_max_x: 100.0
    filter_scope_max_y: 100.0
    filter_scope_max_z: 100.0
```

That is because pointpainting uses roi_sync_param in https://github.com/autowarefoundation/autoware.universe/blob/1ed6fac11a9851c12ede1ec34409204d799d9863/perception/image_projection_based_fusion/launch/pointpainting_fusion.launch.xml#L26

[I checked this PR with evaluator](https://evaluation.tier4.jp/evaluation/oidc/auth/cb/?code=ory_ac_dqcTUSmpfothS_fxY_KIWKER1eENYQQQS6s4LFWsY1g.-gFuMYY_u9fyfAujaRKZ8HeNbnAFTbwmwuIWgs3e5Gk&scope=openid+profile+email+offline_access&state=f9b871c576544626afba41d79798dde7), and I got the error below.

```bash
[ERROR] [launch_ros.actions.load_composable_nodes]: Failed to load node 'pointpainting' of type 'image_projection_based_fusion::PointPaintingFusionNode' in container 'pointcloud_container': Component constructor threw an exception: Statically typed parameter 'filter_scope_min_x' must be initialized.
```

**Review by Shin-kyoto — APPROVED** [review]

**Comment by Shin-kyoto** [comment]
@badai-nguyen 

I did NOT run this PR. I checked the code only. Please check this PR runs correctly.

**Review by miursh — APPROVED** [review]
LGTM!
Could you change the file in [autoware.universe](https://github.com/autowarefoundation/autoware.universe/blob/main/perception/image_projection_based_fusion/config/roi_sync.param.yaml) as well?

**Comment by badai-nguyen** [comment]
@miursh I fogot to link the autoware.universe PR. I already changed here https://github.com/autowarefoundation/autoware.universe/pull/6289. Could you review it as well?

**Pull request merged**
