### PR TITLE
feat(autoware_launch): add point cloud container to localization launch

### PR DESCRIPTION
**Pull request by kaancolak**
Signed-off-by: Kaan Colak <kcolak@leodrive.ai>

## Description
Pass container to localization launch files.

This issue must be merged after this PR :  [https://github.com/autowarefoundation/autoware.universe/pull/2114]( https://github.com/autowarefoundation/autoware.universe/pull/2114)

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [x] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kaancolak** [comment]
@kenji-miyake Hello Miyake-san, Could you assign the appropriate reviewer to this PR?

**Review by YamatoAndo — APPROVED** [review]

**Comment by YamatoAndo** [comment]
@kaancolak Can we merge this PR?

**Comment by kaancolak** [comment]
> @kaancolak Can we merge this PR?

Yes Yamato-san  @YamatoAndo, we can merge this PR.

**Comment by YamatoAndo** [comment]
@kaancolak OK! Once [this PR](https://github.com/autowarefoundation/sample_sensor_kit_launch/pull/48) is approved, let's merge them at the same time.

**Comment by YamatoAndo** [comment]
@kaancolak This PR(https://github.com/autowarefoundation/autoware_launch/pull/129) was merged yesterday, and there is a 
small conflict.
Would you please resolve the conflicting file?

**Comment by kaancolak** [comment]
> @kaancolak This PR(#129) was merged yesterday, and there is a small conflict. Would you please resolve the conflicting file?

I solved the conflict file. It's ready for merge.

**Pull request merged**
