### PR TITLE
feat(processing_time_checker): add five module.

### PR DESCRIPTION
**Pull request by Kazunori-Nakajima**
### Purpose

To be able to check the values of the modules added in the relationship PR in the scenario.

### Merit

To be able to measure module processing time periodically by scenario.And leads to the following
-> Prevention of cycle failures.
-> Suggestion to improve module processing speed.

### Updated

Added 5 module paths to processing_time_checker.yml to read processing_time_pub from the scenario.

## Related links

[discussion slack link](https://star4.slack.com/archives/C03QW0GU6P7/p1727926601208209?thread_ts=1727851666.022839&cid=C03QW0GU6P7)
(I have not discussed this on github.)

## Tests performed

From the red circle in the image, you can see that the value of the module you have just added is retrieved when the scenario is turned on locally. (Sorry for the small text 🙇‍♂)

image

## Notes for reviewers

[Changes on the universe side (already merged)](https://github.com/autowarefoundation/autoware.universe/pull/9065)

### This PR
- processing_time_checker

### [Related PR (universe)](https://github.com/autowarefoundation/autoware.universe/pull/9065)
- /control/control_validator/debug/processing_time_ms
- /control/vehicle_cmd_gate/debug/processing_time_ms
- /planning/scenario_planning/lane_driving/motion_planning/surround_obstacle_checker/debug/processing_time_ms
- /planning/scenario_planning/parking/costmap_generator/debug/processing_time_ms
- /planning/scenario_planning/scenario_selector/debug/processing_time_ms

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].
- [x] The PR has been properly tested.
- [x] The PR has been reviewed by the code owners.

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.
- [ ] The PR is ready for merge.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by kosuke55 — APPROVED** [review]

**Comment by kosuke55** [comment]
looks good to me

@ito-san @isamu-takagi 
could you please approve as a code owner?

**Comment by ito-san** [comment]
@Kazunori-Nakajima @kosuke55 
Please choose either a "Standard Change" or a "Small Change" and fill out the pull request according to the corresponding template, and what is the purpose and benefit of implementing this?

**Comment by Kazunori-Nakajima** [comment]
@ito-san 
The purpose is to be able to read the module processing time from the scenario.
We are looking to improve cycle drop and processing time by adding a condition by processing time to the scenario.

I selected “Standard Change” and filled it out again according to the template.
Please review it again🙇‍♂🙇‍♂🙇‍♂.

**Comment by kosuke55** [comment]
@ito-san kindly ping :bow: :bow:

**Review by ito-san — APPROVED** [review]
LGTM

**Pull request merged**
