### PR TITLE
feat: add gnss/imu localizer 

### PR DESCRIPTION
**Pull request by rsasaki0109**
# Description

This is the PR for integrating GNSS/IMU localizar discussed in the discussion below.
https://github.com/orgs/autowarefoundation/discussions/3257
- ~Add GNSS/IMU localizar parameter files for sample data.~
- ~Introduce ~`localization_mode`~`pose_estimator_mode`(lidar, gnss) parameter in `autoware.launch.xml`  to switch between lidar localization and gnss localization.~
- ~In gnss mode, pose is estimated by gnss instead of ndt.~
- ~You can change the input topic in `autoware_launch/config/localization/eagleye_config.param.yaml`.~
- ~Ensure that sytetem-related parameters are also switched according to the switch between LiDAR/GNSS localization.~

The above conditional branching for each pose estimator and twist estimator within the ` tier4_localization_launch package`  is complex and has been changed.
Instead, we decided to create `map4_localization_launch.xml` in `autoware_launch` and introduce the ` pose_estimator_mode`  parameter in it and switch the pose estimator with that parameter.
A discussion on this is provided below.
1. autoware.universe PR
https://github.com/autowarefoundation/autoware.universe/pull/3063#discussion_r1156921502
3. (This is a private social networking site for the TIEV IV group.)
https://map4-inc.slack.com/archives/CEL0DR2S2/p1680144103464929?thread_ts=1680143206.632879&cid=CEL0DR2S2

pose_estimator_mode in map4_localization_launch.xml   | twist estimator | pose estimator
-- | -- | --
ndt| eagleye_rt(gyro/odom/gnss fusion) | ndt
gnss| eagleye_rt(gyro/odom/gnss fusion) | eagleye_rt(gyro/odom/gnss fusion) 

# Related links

https://github.com/autowarefoundation/autoware/pull/3261
https://github.com/autowarefoundation/autoware.universe/pull/2848
https://github.com/autowarefoundation/autoware-documentation/pull/334

# Tests performed
Localizaiton methods are expected to work as normal, even if they change.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

-  [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The Reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by rsasaki0109** [comment]
I don't know why pre-commit.ci is an error, can the reviewer figure it out?
I did Format Document with prettier.

**Comment by xmfcx** [comment]
> I don't know why pre-commit.ci is an error, can the reviewer figure it out? I did Format Document with prettier.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

If you have the option, could you check **Allow edits from maintainers.** on the right in this PR? I'll try to help.

**Comment by xmfcx** [comment]
Can you rebase this branch to main branch with following commands:
```bash
cd ~/autoware/src/launcher/autoware_launch/
git checkout feat/add_gnss_imu_localizar
git rebase main
git push
```

This might fix the pre-commit, I've merged some PRs to upgrade it.

**Review by kminoda — APPROVED** [review]
LGTM

**Comment by rsasaki0109** [comment]
@yukkysaito @mitsudome-r (@YamatoAndo )
Please also review the PR regarding Eagleye here.

**Review by yukkysaito — APPROVED** [review]
LGTM

**Pull request merged**
