### PR TITLE
feat(system diags): rename diag of ndt scan matcher

### PR DESCRIPTION
**Pull request by YamatoAndo**
## Description

see https://github.com/autowarefoundation/autoware.universe/pull/6889

## Tests performed

see https://github.com/autowarefoundation/autoware.universe/pull/6889

## Effects on system behavior

see https://github.com/autowarefoundation/autoware.universe/pull/6889

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [x] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by YamatoAndo** [comment]
@ito-san @isamu-takagi @takayuki5168 @rej55 @satoshi-ota @shmpwk  https://github.com/autowarefoundation/autoware.universe/pull/6889 has been merged, so I'd like to merge this PR as soon as possible. 
Could you please review this PR?

**Review by isamu-takagi — APPROVED** [review]
LGTM

**Review by ito-san — APPROVED** [review]
LGTM

**Comment by YamatoAndo** [comment]
@takayuki5168 @rej55 @satoshi-ota @shmpwk 
please review :bow:

**Review by shmpwk — APPROVED** [review]

**Pull request merged**
