### PR TITLE
feat(traffic_light_recognition): add tlr args in tier4_perception_component.launch.xml

### PR DESCRIPTION
**Pull request by miursh**
## Description

Add TLR related arguments to tier4_perception_component.launch.xml 

## Tests performed

Not applicable.

## Effects on system behavior

No effects

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by kminoda** [comment]
@miursh I've confirmed that
- With the default args, Autoware launches successfully and the traffic light estimation results are published as intended
- With `traffic_light_recognition/enable_fine_detection:=false`, Autoware launches without `traffic_light_fine_detector`

**Comment by kminoda** [comment]
@miursh I've confirmed that
- With the default args, Autoware launches successfully and the traffic light estimation results are published as intended
- With `traffic_light_recognition/enable_fine_detection:=false`, Autoware launches without `traffic_light_fine_detector`

**Comment by miursh** [comment]
@kminoda 
Thank you for your support. If possible, could you check with AWSIM to ensure that TLR runs without fine_detector?

**Review by kminoda — APPROVED** [review]
LGTM

image
image

**Pull request merged**
