### PR TITLE
feat(planning_simulator): default use_sim_time arg to scenario_simulation

### PR DESCRIPTION
**Pull request by maxime-clem**
## Description

Try to achieve the same thing as https://github.com/autowarefoundation/autoware_launch/pull/746
> In order to set global use_sim_time parameter value to True by default when the simulation is run the use_sim_time argument in the planning_simulator launch file was declared. Its value is set to be equal to the scenario_simulation parameter value.

The issue with the previous PR is that it was overriding any `use_sim_time` argument passed as launch argument, preventing users from running Autoware with `ros2 launch ... use_sim_time:=true`.

## Tests performed

I tested the following with Psim.
| launch argument | `use_sim_time` |
| --- | --- |
| - | `false` |
| `use_sim_time:=true` | `true` |
| `use_sim_time:=false` | `false` |
| `scenario_simulation:=true` | `true` |
| `scenario_simulation:=false` | `false` | 

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [X] I've confirmed the [contribution guidelines].
- [X] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Review by takayuki5168 — APPROVED** [review]

**Comment by maxime-clem** [comment]
@xmfcx @mitsudome-r please review this PR when you can. Thank you.

**Comment by xmfcx** [comment]
cc. @pawellech1

**Review by xmfcx — APPROVED** [review]
Thanks @maxime-clem !

**Comment by pawellech1** [comment]
@maxime-clem I tested your solution and indeed it solves both of the problems. Thank you!

**Pull request merged**
