### PR TITLE
ci: add automatic PR labeler

### PR DESCRIPTION
**Pull request by ktro2828**
## Description

This PR labels PR automatically depending on edited file names.

Following labels should be added:
- component:control
- component:localization
- component:map
- component:perception
- component:planning
- component:sensing
- component:simulation
- component:system

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [x] I've confirmed the [contribution guidelines].
- [x] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

### CODE REVIEW

**Comment by Owen-Liuyuxuan** [comment]
Thanks for the update and contribution.
Personally I also suggest the label for [RViz] `*.rviz` file and [Doc] `*.md file`

**Comment by ktro2828** [comment]
> Thanks for the update and contribution. Personally, I also suggest labels like [RViz] `*.rviz` file and [Doc] `*.md file` to make the labeler more complete.

@Owen-Liuyuxuan Thanks for your suggestion. In that cases, what do you think the suitable name of label for `*.rviz`?

**Comment by Owen-Liuyuxuan** [comment]
For documents, I suggest following AWF/universe:

https://github.com/autowarefoundation/autoware.universe/blob/main/.github/labeler.yaml

```
"type:documentation":
  - docs/**/*
  - "**/*.md"
  - "**/*.rst"
  - "**/*.jpg"
  - "**/*.png"
  - "**/*.svg"
  ```

For RViz, reference are limited, but I would suggest `component:visualization`

**Comment by ktro2828** [comment]
@Owen-Liuyuxuan Sorry for late reaction. I updated the labeler configuration. Could you check this out? https://github.com/autowarefoundation/autoware_launch/pull/972/commits/4e17ef8f66b92cb661c28a528c1cdb70b47edd03

If it is OK, I will add new labels.

**Comment by xmfcx** [comment]
This looks good, once this is done, we need something like https://github.com/lannonbr/issue-label-manager-action on main repositories too. If you have time and you could set it up, I would be very happy.

Until now I've been keeping track of the labels manually in here: https://docs.google.com/spreadsheets/d/1JWQ-PfGamJ_2TO2dM0TV5OQQF1PztpWKIm9O5sI3fQk/edit?usp=sharing

**Comment by xmfcx** [comment]
> For RViz, reference are limited, but I would suggest `component:visualization`

I would go with `component:ui`

**Comment by ktro2828** [comment]
> > For RViz, reference are limited, but I would suggest `component:visualization`
> 
> I would go with `component:ui`

I've applied `component:ui`

**Review by Owen-Liuyuxuan — APPROVED** [review]
Thanks for the udpates and contribution. I do not have further comment.

**Comment by ktro2828** [comment]
I added new corresponding labels 
- `type:**`: https://github.com/autowarefoundation/autoware_launch/labels?q=type
- `component:**`: https://github.com/autowarefoundation/autoware_launch/labels?q=component

**Pull request merged**
